name: taylorswift
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Added for professional Windows Installers
  inno_bundle: ^0.11.2 

flutter:
  uses-material-design: true

# This section configures the Windows Setup Wizard
inno_bundle:
  # This is a unique Windows GUID generated for your app
  id: {0B8C24D3-A1B2-4E5F-BD7C-8D4A228B1234}
  name: Taylor Swift App
  publisher: Samson Oyieyo
  display_name: Taylor Swift App
  # Optional: executable_name: TaylorSwift (defaults to package name)
