name: taylorswift
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Added for professional Windows Installers
  inno_bundle: ^0.11.2 

flutter:
  uses-material-design: true

# This section configures the Windows Setup Wizard
inno_bundle:
  id: com.samsonoyieyo.taylorswift
  name: Taylor Swift App
  publisher: Samson Oyieyo
  display_name: Taylor Swift App
  # Optional: executable_name: TaylorSwift (defaults to package name)
